package com.harmex.deathcube.world.skill;

import com.google.common.collect.ImmutableMap;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

public class SkillUtils {
    public static final ImmutableMap<Item, Float> XP_FOR_ITEM_FISHED =
            ImmutableMap.<Item, Float>builder()
                    .put(Items.COD, 10.0F)
                    .put(Items.SALMON, 25.0F)
                    .put(Items.TROPICAL_FISH, 50.0F)
                    .put(Items.PUFFERFISH, 40.0F)
                    .put(Items.LILY_PAD, 5.0F)
                    .put(Items.LEATHER_BOOTS, 10.0F)
                    .put(Items.LEATHER, 5.0F)
                    .put(Items.BONE, 5.0F)
                    .put(Items.POTION, 5.0F)
                    .put(Items.STRING, 5.0F)
                    .put(Items.FISHING_ROD, 50.0F)
                    .put(Items.BOWL, 5.0F)
                    .put(Items.STICK, 5.0F)
                    .put(Items.INK_SAC, 5.0F)
                    .put(Items.TRIPWIRE_HOOK, 5.0F)
                    .put(Items.ROTTEN_FLESH, 5.0F)
                    .put(Items.BAMBOO, 5.0F)
                    .put(Items.NAME_TAG, 40.0F)
                    .put(Items.SADDLE, 40.0F)
                    .put(Items.BOW, 50.0F)
                    .put(Items.ENCHANTED_BOOK, 50.0F)
                    .put(Items.NAUTILUS_SHELL, 75.0F)
                    .build();

    public static final ImmutableMap<Block, Float> XP_FOR_BLOCK_MINED =
            ImmutableMap.<Block, Float>builder()
                    .put(Blocks.STONE, 2.5F)
                    .put(Blocks.GRANITE, 2.5F)
                    .put(Blocks.DIORITE, 2.5F)
                    .put(Blocks.ANDESITE, 2.5F)
                    .put(Blocks.COAL_ORE, 7.5F)
                    .put(Blocks.DEEPSLATE_COAL_ORE, 7.5F)
                    .put(Blocks.IRON_ORE, 12.5F)
                    .put(Blocks.DEEPSLATE_IRON_ORE, 12.5F)
                    .put(Blocks.GOLD_ORE, 25.0F)
                    .put(Blocks.DEEPSLATE_GOLD_ORE, 25.0F)
                    .put(Blocks.LAPIS_ORE, 17.5F)
                    .put(Blocks.DEEPSLATE_LAPIS_ORE, 17.5F)
                    .put(Blocks.REDSTONE_ORE, 17.5F)
                    .put(Blocks.DEEPSLATE_REDSTONE_ORE, 17.5F)
                    .put(Blocks.DIAMOND_ORE, 50.0F)
                    .put(Blocks.DEEPSLATE_DIAMOND_ORE, 50.0F)
                    .put(Blocks.EMERALD_ORE, 50.0F)
                    .put(Blocks.DEEPSLATE_EMERALD_ORE, 50.0F)
                    .put(Blocks.NETHERRACK, 2.5F)
                    .put(Blocks.NETHER_QUARTZ_ORE, 20.0F)
                    .put(Blocks.NETHER_GOLD_ORE, 20.0F)
                    .put(Blocks.SANDSTONE, 2.5F)
                    .put(Blocks.RED_SANDSTONE, 2.5F)
                    .put(Blocks.OBSIDIAN, 75.0F)
                    .put(Blocks.BASALT, 2.5F)
                    .put(Blocks.BLACKSTONE, 2.5F)
                    .put(Blocks.WHITE_TERRACOTTA, 2.5F)
                    .put(Blocks.ORANGE_TERRACOTTA, 2.5F)
                    .put(Blocks.MAGENTA_TERRACOTTA, 2.5F)
                    .put(Blocks.LIGHT_BLUE_TERRACOTTA, 2.5F)
                    .put(Blocks.YELLOW_TERRACOTTA, 2.5F)
                    .put(Blocks.LIME_TERRACOTTA, 2.5F)
                    .put(Blocks.PINK_TERRACOTTA, 2.5F)
                    .put(Blocks.GRAY_TERRACOTTA, 2.5F)
                    .put(Blocks.LIGHT_GRAY_TERRACOTTA, 2.5F)
                    .put(Blocks.CYAN_TERRACOTTA, 2.5F)
                    .put(Blocks.PURPLE_TERRACOTTA, 2.5F)
                    .put(Blocks.BLUE_TERRACOTTA, 2.5F)
                    .put(Blocks.BROWN_TERRACOTTA, 2.5F)
                    .put(Blocks.GREEN_TERRACOTTA, 2.5F)
                    .put(Blocks.RED_TERRACOTTA, 2.5F)
                    .put(Blocks.BLACK_TERRACOTTA, 2.5F)
                    .put(Blocks.TERRACOTTA, 2.5F)
                    .put(Blocks.TUFF, 2.5F)
                    .put(Blocks.DEEPSLATE, 2.5F)
                    .put(Blocks.CALCITE, 10F)
                    .put(Blocks.AMETHYST_BLOCK, 10F)
                    .put(Blocks.AMETHYST_CLUSTER, 10F)
                    .put(Blocks.SMALL_AMETHYST_BUD, 5F)
                    .put(Blocks.MEDIUM_AMETHYST_BUD, 10F)
                    .put(Blocks.LARGE_AMETHYST_BUD, 20F)
                    .put(Blocks.DRIPSTONE_BLOCK, 2.5F)
                    .put(Blocks.END_STONE, 5.0F)
                    .build();

    public static final ImmutableMap<Block, Float> XP_FOR_CROP_HARVESTED =
            ImmutableMap.<Block, Float>builder()
                    .put(Blocks.WHEAT, 2.5F)
                    .put(Blocks.CARROTS, 5.0F)
                    .put(Blocks.POTATOES, 5.0F)
                    .put(Blocks.BEETROOTS, 5.0F)
                    .put(Blocks.SUGAR_CANE, 5.0F)
                    .put(Blocks.PUMPKIN, 5.0F)
                    .put(Blocks.MELON, 5.0F)
                    .put(Blocks.GRASS, 5.0F)
                    .put(Blocks.TALL_GRASS, 5.0F)
                    .put(Blocks.SEAGRASS, 5.0F)
                    .put(Blocks.TALL_SEAGRASS, 5.0F)
                    .build();
}
